### ISSUE TITLE
Descargar las imágenes de los posts de instagram y mandarlas como galería

### ISSUE THREAD

**Issue by fauno** [catdevnull/dlbot4#6]
O al menos responder con el link reemplazando el hostname por ddinstagram.com para que se pueda ver la imagen del post como vista previa (pero sería una sola)

**Comment by catdevnull** [comment]
genial, de hecho ya lo hacemos para TikTok. pero hay que ver como hacerlo porque parece que cobalt.tools no lo soporta, así que tendré que hacer nuestra propia implementacion (o implementarlo en cobalt!)

**Comment by catdevnull** [comment]
supongo que cobalt lo habra implementado porque ahora parece funcionar pero no funciona con algunos posts como https://www.instagram.com/p/DBZllBFz-Dp/?utm_source=ig_web_copy_link, tengo que investigar

**Comment by catdevnull** [comment]
ah, hay que separarlos en varios albumes de telegram: error: ETELEGRAM: 400 Bad Request: too many messages to send as an album
abro otro issue
